### ISSUE TITLE
Select Database 

### ISSUE THREAD

**Issue by diamondjira2020** [VasiliyNovikov/RedisCore#32]
hi
how to select database number in redis connection?

**Comment by viktor-ferenczi** [comment]
https://redis.io/commands/select/

**Comment by diamondjira2020** [comment]
i known this.
my ask is how to select db number by your component???
constructors in this component just get uri!

**Comment by mhsankar** [comment]
Hi .
Please help me how can i read data from another db.
For example i have some data in db number 2
How i can config my redis client to read data from db number 2?

**Comment by mhsankar** [comment]
how can run a command like `select db2` in your component?

**Comment by VasiliyNovikov** [comment]
This functionality is not currently supported. I'll try to find some time to implement it, otherwise you can propose a PR that implements it

**Comment by VasiliyNovikov** [comment]
Here we go: #33

**Comment by VasiliyNovikov** [comment]
You'll be able to specify the database index in the config:
```cs
var config = new RedisClientConfig(uri)
config.Database = dbIndex;
```
